//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRecruting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TVA { get; set; }
    
        public virtual CandidateBill CandidateBill { get; set; }
        public virtual CompanyBill CompanyBill { get; set; }
    }
}
