//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMRecruting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVXTraining
    {
        public int Id { get; set; }
        public Nullable<int> CvId { get; set; }
        public Nullable<int> TrainingId { get; set; }
    
        public virtual CV CV { get; set; }
        public virtual Training Training { get; set; }
    }
}
